# Rlease is Required (Espically `release` keyword) for publishing CI Component To CI / CD Catalog
# See: https://docs.gitlab.com/ci/components/#publish-a-new-release
#
# create-release:
#   stage: release
#   image: registry.gitlab.com/gitlab-org/release-cli:latest
#   script: echo "Creating release $CI_COMMIT_TAG"
#   rules:
#     - if: $CI_COMMIT_TAG
#   release:
#     tag_name: $CI_COMMIT_TAG
#     description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
